### PR TITLE
Fix typo for auto_detect_ep function

### PR DESCRIPTION
**Pull request by mengniwang95**
## Type of Change

bug fix

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]

**Comment by mengniwang95** [comment]
it seems the CI failure is due to latest torch can't export > 2GB model to ONNX model:
https://github.com/pytorch/pytorch/issues/132205
https://github.com/huggingface/optimum/issues/1800

**Comment by Crafter-san** [comment]
@hshen14 it's been 4 days since the provided changes were approved, please merge

**Comment by thuang6** [comment]
> @hshen14 it's been 4 days since the provided changes were approved, please merge

@Crafter-san，since there is no available solution to fix export issue on latest Torch currently, we are trying to find out the proper Torch version, which will be limited in CI test.  The PR will be merged soon after this walk around applied in CI

**Comment by mengniwang95** [comment]
Unit Test ONNXRT baseline runs the unittest of main branch, its failure makes sense.
Unit Test ONNXRT runs the unittest of this PR's branch, it has passed.
So we can merge this PR

**Comment by Crafter-san** [comment]
@thuang6 here is the possible offender for the size limit: https://github.com/pytorch/pytorch/issues/132205
If you could share this with the rest of the team, you guys could possibly go through and fix the issue and make a pull request. I don't have enough Python experience to fix the issue myself.

**Comment by Crafter-san** [comment]
additionally, the issue is within it requiring a filename to properly write it to a file. I don't know how, but perhaps including an arg for filename, and a default filename (for people using things like Optimum CLI that don't have access to the direct args)

**Comment by Crafter-san** [comment]
Pytorch issue is in the process of being fixed: https://github.com/pytorch/pytorch/pull/140962
It will soon merge and hopefully fix export issues

**Comment by Crafter-san** [comment]
Reversion complete
https://github.com/pytorch/pytorch/pull/140961
https://github.com/pytorch/pytorch/pull/140962
Please act accordingly

**Comment by mengniwang95** [comment]
> Reversion complete [pytorch/pytorch#140961](https://github.com/pytorch/pytorch/pull/140961) [pytorch/pytorch#140962](https://github.com/pytorch/pytorch/pull/140962) Please act accordingly

Hi, thank you for your reminder, we will remove the version control after torch latest version is released which contains this commit.

**Comment by Crafter-san** [comment]
@mengniwang95 when will it be fixed? There's no new versions/releases

**Comment by mengniwang95** [comment]
Hi @Crafter-san , this fix is in pytorch source code and now what we need to do is waiting for the new release of pytorch to fix this issue. If you failed to export onnx model due to this issue, you can downgrade your pytorch version or build pytorch from its main branch source code.

**Pull request merged**
